name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Install goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Build production binary
        run: |
          chmod +x ./scripts/buildprod.sh
          ./scripts/buildprod.sh

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: notely-482821
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Build & push image to Artifact Registry
        run: |
          gcloud builds submit --tag us-central1-docker.pkg.dev/notely-482821/notely-ar-repo/notely:latest .

      - name: Run migrations
        run: |
          chmod +x ./scripts/migrateup.sh
          ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/notely-482821/notely-ar-repo/notely:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project notely-482821 \
            --max-instances=4
